### ISSUE TITLE
显示问题

### ISSUE THREAD

**Issue by taseikyo** [cnfeat/GoodThingList#14]
[好博客清单](https://github.com/cnfeat/GoodThingList/blob/master/GoodBlogList.md) 下的 [好·博客列表](https://github.com/cnfeat/GoodThingList/blob/master/GoodBlogList.md#%E5%A5%BD%E5%8D%9A%E5%AE%A2%E5%88%97%E8%A1%A8) 显示有问题😂具体见下图
![screenshot](https://user-images.githubusercontent.com/23132915/53627475-89917f00-3c43-11e9-9b8a-320f92e18d9f.png)

**Comment by cnfeat** [comment]
已修复，谢谢提醒。
