### ISSUE TITLE
MWeb 主题分享：Material-Theme-Darker 

### ISSUE THREAD

**Issue by cnfeat** [cnfeat/GoodThingList#5]
俺平时写 Markdown 使用 Sublime 为主，Mweb 为辅。

Sublime 常用主题是 Material-Theme，偶尔切换使用 MWeb 自带主题不习惯，于是便按着  Material-Theme 的颜色做了适配 MWeb 的主题。

下载地址：[GoodThingList/MWebTheme at master · cnfeat/GoodThingList](https://github.com/cnfeat/GoodThingList/tree/master/MWebTheme)

使用效果图如下

![](http://openmindclub.qiniudn.com/omt/MWebCSS.jpg)
## 使用方法

将 Material-Theme-Darker.style 放在以下文件夹。

`~/Library/Containers/com.coderforart.MWeb/Data/Documents/themes/EditorThemes/`

然后在 MWeb 的主题设置启用即可。
## 参考链接
- [material-theme: Material Theme](https://github.com/equinusocio/material-theme)
- [Mattia Astorino | Web Designer & Developer](http://equinsuocha.io/material-theme/)
## ChangeLog
- 2016-10-09 陈素封 创建

**Comment by CYsuncheng** [comment]
感谢
