### ISSUE TITLE
博主的cnfeat.github.io 为什么不开issue呢？

### ISSUE THREAD

**Issue by BruceZhaoR** [cnfeat/GoodThingList#7]
今天无意浏览到了博主的博客 <http://cnfeat.com> 发现`back-to-top` 有一些问题，准备弄一个PR给你。
你可以参考这里

`_includes/head.html` 里面加入所需的js库：

https://github.com/BruceZhaoR/brucezhaor.github.io/blob/master/_layouts/default.html#L81-L82

`_layouts/default.html里面加入图标和相应的动作脚本：

https://github.com/BruceZhaoR/brucezhaor.github.io/blob/master/_layouts/default.html#L108-L132

`css/backtop.css`  换成 ：

https://github.com/BruceZhaoR/brucezhaor.github.io/blob/master/assets/css/style-old.css#L837-L871

最后的结果是我这个网站：

http://brucezhaor.github.io  😊

**Comment by cnfeat** [comment]
你好，经提醒，已经开 issue 了 > https://github.com/cnfeat/cnfeat.github.io

但我发现打开你的博客也没有发现 back-to-top 的图标？是否我没发现？

**Comment by BruceZhaoR** [comment]
我写了一个js监听鼠标滑动，你鼠标向下滑动250px, 就会出现图表。:smile: @cnfeat

**Comment by cnfeat** [comment]
oh，原来是 ADblock 了没看见，你可以 PR 了哈~

**Comment by BruceZhaoR** [comment]
@cnfeat please check and merge.
